#######################################
# System Health Check API
#######################################

### [1.1] Basic Health Check
# @name ping
GET {{baseUrl}}/ping
Content-Type: application/json
