name: build-and-push-main

on:
  push:
    branches: ["main"]
    paths:
      - "backend/**"
      - ".github/**"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "23"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install --include=dev

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          push: true
          tags: ${{ vars.DOCKERHUB_IMAGE_NAME }}:main

  update-on-server:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Remote SSH Commands
        uses: fifsky/ssh-action@v0.0.6
        with:
          command: |
            sudo docker compose -f ${{ vars.DOCKER_FILE_BACKEND }} pull
            sudo docker compose -f ${{ vars.DOCKER_FILE_BACKEND }} up -d
            sudo docker image prune -f
          host: ${{ vars.MAIN_HOST }}
          user: ${{ vars.MAIN_USERNAME }}
          key: ${{ secrets.MAIN_SSH_KEY }}
